project:
  type: website
  output-dir: docs

website:
  title: "Nate Whybra"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: lectures.qmd
        text: Lectures
      - href: notes.qmd
        text: Notes
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    math: mathjax



