project:
  type: website
  output-dir: docs

website:
  title: "Nathan Whybra"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: lectures.qmd
        text: Lectures
      - href: notes.qmd
        text: Notes
      - href: cv.qmd
        text: CV

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    default-theme: darkl
    css: styles.css
    toc: true
    math: mathjax



